// svelte/src/App.svelte
<script lang="ts">
    import TextInput from "./lib/components/TextInput.svelte";
    import SelectInput from "./lib/components/SelectInput.svelte";
    import { accountData } from "./lib/stores/accountData";

    const choices: Array<string> = ["Compiègne", "Paris", "Amiens"];

    $: isError = Object.values($accountData).some((d) => "" !== d.error);
    $: $accountData, accountData.handleErrors();

    function onSubmit(): void {
        if (!isError) {
            alert(JSON.stringify(Object.values($accountData).map((d) => d.value)));
        }
    }
</script>

<main class="app">
    <h1>Svelte</h1>
    <form id="form" on:submit|preventDefault={onSubmit}>
        <TextInput
            name="username"
            type="text"
            label="Nom d'utilisateur"
            placeholder="Jean"
            bind:value={$accountData.username.value}
            error={$accountData.username.error}
            touched={$accountData.username.touched}
            on:change|once={() => accountData.setTouched("username")}
        />
        <TextInput
            name="email"
            type="email"
            label="Adresse email"
            placeholder="jean@gmail.com"
            bind:value={$accountData.email.value}
            error={$accountData.email.error}
            touched={$accountData.email.touched}
            on:change|once={() => accountData.setTouched("email")}
        />
        <TextInput
            name="phoneNumber"
            type="tel"
            label="Numéro de téléphone"
            placeholder="0690805542"
            bind:value={$accountData.phoneNumber.value}
            error={$accountData.phoneNumber.error}
            touched={$accountData.phoneNumber.touched}
            on:change|once={() => accountData.setTouched("phoneNumber")}
        />
        <TextInput
            name="password"
            type="password"
            label="Mot de passe"
            bind:value={$accountData.password.value}
            error={$accountData.password.error}
            touched={$accountData.password.touched}
            on:change|once={() => accountData.setTouched("password")}
        />
        <SelectInput
            name="city"
            label="Ville"
            bind:value={$accountData.city.value}
            error={$accountData.city.error}
            touched={$accountData.city.touched}
            {choices}
            on:change|once={() => accountData.setTouched("city")}
        />
    </form>
    <button type="submit" form="form" class:disabled={isError} disabled={isError}>Envoyer</button>
</main>

<style>
    h1 {
        font-size: 3.2em;
        line-height: 1.1;
    }

    .app {
        background-color: #ffffff;
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-direction: column;
        padding: 25px;
        box-shadow: 12px 12px 2px 1px rgba(0, 0, 255, 0.2);
        min-width: 320px;
    }

    form {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        width: 100%;
        margin: 20px 0;
    }

    button {
        border-radius: 8px;
        border: 1px solid transparent;
        padding: 0.6em 1.2em;
        font-size: 1em;
        font-weight: 500;
        font-family: inherit;
        background-color: #2d8565;
        cursor: pointer;
        transition: border-color 0.25s;
        color: #ffffff;
    }
    button:hover:not(.disabled) {
        border-color: #14440b;
    }
    button:focus:not(.disabled),
    button:focus-visible:not(.disabled) {
        outline: 4px auto -webkit-focus-ring-color;
    }
    button.disabled {
        opacity: 0.5;
        background-color: #42b88c;
        cursor: not-allowed;
    }
</style>

// react/src/App.tsx
import { useState } from "react";

import SelectInput from "./components/SelectInput";
import TextInput from "./components/TextInput";
import { FormDataType, initialFormData } from "./data/formData";

function App() {
    const cities: Array<string> = ["Compiègne", "Paris", "Amiens"];
    const [isError, setIsError] = useState<boolean>(true);
    const [formData, setFormData] = useState<FormDataType>(initialFormData);

    const handleErrors = (formData: FormDataType) => {
        for (const field in formData) {
            const fieldData = formData[field];
            const value = fieldData.value;
            const requirements = fieldData.requirements;
            const regexRequirement = requirements?.regex ? new RegExp(requirements.regex) : null;

            let error = "";

            if (requirements) {
                if (false === requirements.empty && "" === value) {
                    error = requirements.emptyMessage ?? "Cette valeur ne peut pas être vide.";
                } else if (regexRequirement && !regexRequirement.test(value)) {
                    error = requirements.regexMessage ?? "Cette valeur n'est pas valide.";
                }
            }

            formData[field] = { ...formData[field], error };
        }

        return formData;
    };

    const handleChange = (event: React.FormEvent<HTMLInputElement | HTMLSelectElement>) => {
        const target = event.target as HTMLInputElement;
        let newFormData = formData;

        if (target.name in newFormData) {
            const value = target.value;

            newFormData = { ...newFormData, [target.name]: { ...newFormData[target.name], value, touched: true } };
        }

        newFormData = handleErrors(newFormData);

        setFormData(newFormData);
        setIsError(Object.values(newFormData).some((d) => "" !== d.error));
    };

    const onSubmit = (event: React.SyntheticEvent) => {
        event.preventDefault();

        if (!isError) {
            alert(JSON.stringify(Object.values(formData).map((d) => d.value)));
        }
    };

    return (
        <div className="app">
            <h1>React</h1>
            <form id="form" onSubmit={onSubmit}>
                <TextInput
                    name="username"
                    value={formData.username.value}
                    error={formData.username.error}
                    touched={formData.username.touched}
                    type="text"
                    label="Nom d'utilisateur"
                    placeholder="Jean"
                    onChange={handleChange}
                />
                <TextInput
                    name="email"
                    value={formData.email.value}
                    error={formData.email.error}
                    touched={formData.email.touched}
                    type="email"
                    label="Adresse email"
                    placeholder="jean@gmail.com"
                    onChange={handleChange}
                />
                <TextInput
                    name="phoneNumber"
                    value={formData.phoneNumber.value}
                    error={formData.phoneNumber.error}
                    touched={formData.phoneNumber.touched}
                    type="tel"
                    label="Numéro de téléphone"
                    placeholder="0690805542"
                    onChange={handleChange}
                />
                <TextInput
                    name="password"
                    value={formData.password.value}
                    error={formData.password.error}
                    touched={formData.password.touched}
                    type="password"
                    label="Mot de passe"
                    onChange={handleChange}
                />
                <SelectInput
                    name="city"
                    value={formData.city.value}
                    error={formData.city.error}
                    touched={formData.city.touched}
                    label="Ville"
                    choices={cities}
                    onChange={handleChange}
                />
            </form>
            <button type="submit" form="form" className={`${isError ? "disabled" : ""}`} disabled={isError}>
                Envoyer
            </button>
        </div>
    );
}

export default App;
