// react/src/components/SelectInput.tsx
import { useEffect, useState } from "react";

const SelectInput = ({ label, name, touched = false, choices, error = "", children, ...props }: SelectInputType) => {
    const [isError, setIsError] = useState(false);

    useEffect(() => {
        setIsError(touched && "" !== error);
    }, [touched, error]);

    return (
        <div className="input-group">
            <label className="input-label" htmlFor={name}>
                {label}
            </label>
            <select {...props} name={name} id={name} className={`${isError ? "invalid" : ""} ${props.className ?? ""}`}>
                <option value="" />
                {choices.map((choice, index) => (
                    <option value={choice} key={choice + index}>
                        {choice}
                    </option>
                ))}
            </select>
            <span className="input-error">{isError && error}</span>
            {children}
        </div>
    );
};

export default SelectInput;

export interface SelectInputType {
    label: string;
    name: string;
    touched?: boolean;
    choices: Array<string>;
    error?: string;
    children?: any;
    [propName: string]: any;
}

// svelte/src/lib/components/SelectInput.svelte
<script lang="ts">
    export let label: string = "";
    export let name: string;
    export let error: string = "";
    export let touched: boolean = true;
    export let choices: Array<string>;
    export let value: string = "";

    $: isError = error !== "" && touched;
</script>

<div class="input-group">
    <label class="input-label" for={name}>
        <slot name="label">
            {label}
        </slot>
    </label>
    <select {...$$restProps} class:invalid={isError} bind:value {name} id={name} on:change on:change>
        <slot name="select">
            <option value="" />
            {#each choices as choice}
                <option value={choice}>
                    {choice}
                </option>
            {/each}
        </slot>
    </select>
    <span class="input-error">
        <slot name="error" {isError}>
            {#if isError}
                {error}
            {/if}
        </slot>
    </span>
    <slot />
</div>

<style>
    @import "./inputs.css";
</style>
