// react/src/components/TextInput.tsx
import { useEffect, useState } from "react";

const TextInput = ({ label, name, touched = true, type, error = "", children, ...props }: TextInputType) => {
    const [isError, setIsError] = useState(false);

    useEffect(() => {
        setIsError(Boolean(touched && "" !== error));
    }, [touched, error]);

    return (
        <div className="input-group">
            <label className="input-label" htmlFor={name}>
                {label}
            </label>
            <input {...props} className={`${isError ? "invalid" : ""} ${props.className ?? ""}`} name={name} id={name} type={type} />
            <span className="input-error">{isError && error}</span>
            {children}
        </div>
    );
};

export default TextInput;

export interface TextInputType {
    label: string;
    name: string;
    touched?: boolean;
    type: "text" | "tel" | "email" | "password";
    error?: string;
    children?: any;
    [propName: string]: any;
}

// svelte/src/lib/components/TextInput.svelte
<script lang="ts">
    export let label: string = "";
    export let name: string;
    export let error: string = "";
    export let touched: boolean = true;
    export let type: "text" | "email" | "tel" | "password" = "text";
    export let value: string;

    $: isError = error !== "" && touched;

    function typeAction(node: HTMLInputElement): void {
        node.type = type;
    }
</script>

<div class="input-group">
    <label class="input-label" for={name}>
        <slot name="label">
            {label}
        </slot>
    </label>
    <input use:typeAction {...$$restProps} class:invalid={isError} bind:value {name} id={name} on:input on:blur />
    <span class="input-error">
        <slot name="error" {isError}>
            {#if isError}
                {error}
            {/if}
        </slot>
    </span>
    <slot />
</div>

<style>
    @import "./inputs.css";
</style>
